caso1:
	g++ main.cpp linkedList.cpp -o caso1.o

#all: comm_progs

#comm_progs:
#	g++ -o news.o news.cpp -lcurl

# docker run -it --rm -v "C:\dev\cursostec\estructuras\1. SemestreII2023\support\http:/home" gcc bash
# apt update -y
# apt install curl




# docker run -it --rm -v C:\Users\migue\Documents\EstructuraDatos\RepoSemestre\Caso#1\Preliminar#2:/home gcc bash